version: '3.7'
services:
  webapp:
    image: tomcat-base
    environment:
      - CATALINA_HOME
    networks:
      - rdbms-net
    ports:
      - "8080:8080"
      - "4000:4000"
    volumes:
      - .:/target:delegated
      - ./glowroot:/glowroot:delegated
      - ~/.m2/repository/ServletFilterExample/ServletFilterExample/1.0-SNAPSHOT/ServletFilterExample-1.0-SNAPSHOT.war:$CATALINA_HOME/webapps/ServletFilterExample.war

  h2:
    image: buildo/h2database@sha256:4366082b5832c01cb61ed732bca112f27a6e9bfa9e08f19110aa2ed121025127
    #environment:
    #  - H2_OPTIONS=-ifNotExists # Allow creating database automatically on connection
    ports:
      - "1521:1521" # TCP
      - "8081:8082"   # web console
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - rdbms-net

networks:
  rdbms-net:
    name: rdbms-net
